export type Locale = "en" | "ar";

export const contactContent = {
  en: {
    heading: "Get in touch.",
    description: "We'd welcome the chance to hear from you. Every introduction is treated with complete discretion.",
    badge: "Typically responds within one business day",
    contactLabel: "Contact",
    addressLabel: "Address",
    name: "Dr. Ahmed Ismail Alfarooque",
    phone: "+966 53 333 9052",
    phoneHref: "+966533339052",
    email: "ceo@qmulate.com",
    address: ["King Abdulaziz Rd, Albasatin Dist.", "P.O. Box 23718, Jeddah 9351", "Kingdom of Saudi Arabia"],
    eyebrow: "Introduction Request",
    formHeading: "Begin a private conversation.",
    fields: {
      fullName: "Full Name",
      fullNamePlaceholder: "Your full name",
      email: "Email Address",
      emailPlaceholder: "you@example.com",
      entity: "Family / Entity Name",
      entityPlaceholder: "Family, company, or endowment name",
      area: "Area of Interest",
      areaPlaceholder: "Select an area",
      message: "Message",
      messagePlaceholder: "Tell us briefly what you'd like to discuss…",
    },
    areas: [
      "Ownership Structuring & Governance",
      "Real Estate Asset Management",
      "Development & Investment",
      "General Enquiry",
    ],
    send: "Send introduction →",
    sending: "Sending…",
    sentHeading: "Introduction received.",
    sentBody: "We'll be in touch within one business day. Every communication is private and confidential.",
    required: "*",
  },
  ar: {
    heading: "تواصل معنا.",
    description: "يسعدنا خدمتكم من خلال نموذج التواصل التالي وفريقنا سيكون على استعداد تام للرد بأقرب فرصة ممكنة.",
    badge: "نردّ عادةً في غضون يوم عمل واحد",
    contactLabel: "التواصل",
    addressLabel: "العنوان",
    name: "د. أحمد إسماعيل الفاروقي",
    phone: "+966 53 333 9052",
    phoneHref: "+966533339052",
    email: "ceo@qmulate.com",
    address: ["طريق الملك عبدالعزيز، حي البساتين", "ص.ب 23718، جدة 9351", "المملكة العربية السعودية"],
    eyebrow: "طلب تقديم",
    formHeading: "ابدأ محادثة خاصة.",
    fields: {
      fullName: "الاسم الكامل",
      fullNamePlaceholder: "اسمك الكامل",
      email: "البريد الإلكتروني",
      emailPlaceholder: "example@domain.com",
      entity: "اسم العائلة / الجهة",
      entityPlaceholder: "اسم العائلة، الشركة، أو الوقف",
      area: "مجال الاهتمام",
      areaPlaceholder: "اختر مجالاً",
      message: "الرسالة",
      messagePlaceholder: "أخبرنا باختصار عن موضوع النقاش…",
    },
    areas: [
      "هيكلة الملكية والحوكمة",
      "إدارة الأصول العقارية",
      "التطوير والاستثمار",
      "استفسار عام",
    ],
    send: "← إرسال الطلب",
    sending: "جارٍ الإرسال…",
    sentHeading: "تم استلام طلبك.",
    sentBody: "سنتواصل معك خلال يوم عمل واحد. كل مراسلة خاصة وسرية.",
    required: "*",
  },
} satisfies Record<Locale, Record<string, unknown>>;
